# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard :rspec, cmd: 'bundle exec rspec' do
  watch(%r{^spec/.+_spec\.rb$})
  watch('spec/spec_helper.rb')  { 'spec' }
  watch('hansard.rb') { 'spec/hansard_spec.rb' }
#  watch('hansard_viz/hansard.rb') { 'spec' }
#  watch('hansard_viz/pattern_counter.rb') { 'spec/pattern_counter_spec.rb' }
#  watch('hansard_viz/template.erb') { 'spec' }
end

